#!/usr/bin/env node

/**
 * update-readme.js - Update README.md with the latest PR section.
 *
 * Usage:
 *   node update-readme.js
 *
 * This script reads the PR section generated by fetch-prs.js and replaces
 * the old section in README.md between the markers:
 *   <!-- PR_SECTION_START -->
 *   <!-- PR_SECTION_END -->
 *
 * Environment variables:
 *   COMMIT_AUTHOR_NAME  - Git author name for the commit (default: "GitHub Actions")
 *   COMMIT_AUTHOR_EMAIL - Git author email (default: "actions@github.com")
 *   DRY_RUN             - Set to "true" to preview changes without committing
 *   PR_BRANCH           - Branch to create the PR against (default: main)
 */

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

// ─── Configuration ───────────────────────────────────────────────────────────

// Resolve paths relative to the repo root (parent of .github/)
// Use __filename so __dirname is always correct even when run from any directory
const SCRIPT_DIR = path.dirname(__filename);
const REPO_ROOT = path.resolve(SCRIPT_DIR, "../..");
const README_PATH = path.join(REPO_ROOT, "README.md");
const PR_SECTION_PATH = "/tmp/poliglots-prs.md";
const START_MARKER = "<!-- PR_SECTION_START -->";
const END_MARKER = "<!-- PR_SECTION_END -->";

const DRY_RUN = process.env.DRY_RUN === "true";
const AUTHOR_NAME = process.env.COMMIT_AUTHOR_NAME || "GitHub Actions";
const AUTHOR_EMAIL = process.env.COMMIT_AUTHOR_EMAIL || "actions@github.com";
const TARGET_BRANCH = process.env.PR_BRANCH || "main";

// ─── Helpers ─────────────────────────────────────────────────────────────────

function run(cmd, cwd = null) {
  return execSync(cmd, {
    encoding: "utf8",
    cwd: cwd || REPO_ROOT,
    stdio: ["pipe", "pipe", "pipe"],
  }).trim();
}

function main() {

  console.log("📖 Reading new PR section...");
  if (!fs.existsSync(PR_SECTION_PATH)) {
    console.error("❌ PR section not found. Run fetch-prs.js first.");
    process.exit(1);
  }
  const newSection = fs.readFileSync(PR_SECTION_PATH, "utf8");

  console.log("📖 Reading README.md...");
  const readme = fs.readFileSync(README_PATH, "utf8");

  // Check if markers exist
  const startIdx = readme.indexOf(START_MARKER);
  const endIdx = readme.indexOf(END_MARKER);

  let newReadme;
  if (startIdx === -1 || endIdx === -1) {
    // Markers don't exist — append before the Stats section
    console.log("⚠️  Markers not found. Appending after existing contributions section.");
    const existingContribIndex = readme.indexOf("## 🌟 Open Source Contributions");
    if (existingContribIndex !== -1) {
      const statsIndex = readme.indexOf("## 📊 GitHub Stats");
      if (statsIndex !== -1) {
        newReadme =
          readme.substring(0, statsIndex) +
          START_MARKER +
          "\n" +
          newSection +
          "\n" +
          END_MARKER +
          readme.substring(statsIndex);
      } else {
        console.error(
          "❌ Could not find '## 📊 GitHub Stats' to place the PR section."
        );
        process.exit(1);
      }
    } else {
      console.error(
        "❌ Could not find existing contributions section to append to."
      );
      process.exit(1);
    }
  } else {
    // Replace existing section
    newReadme =
      readme.substring(0, startIdx) +
      START_MARKER +
      "\n" +
      newSection +
      "\n" +
      END_MARKER +
      readme.substring(endIdx + END_MARKER.length);
  }

  // Check if anything actually changed
  if (newReadme === readme) {
    console.log("✅ No changes needed. README.md is up to date.");
    process.exit(0);
  }

  console.log("✅ New PR section generated!");

  if (DRY_RUN) {
    console.log("\n--- DRY RUN — Changes that would be made ---");
    // Show diff
    const currentLines = readme.split("\n");
    const newLines = newReadme.split("\n");
    const maxLen = Math.max(currentLines.length, newLines.length);
    for (let i = 0; i < maxLen; i++) {
      const curr = currentLines[i] || "";
      const nw = newLines[i] || "";
      if (curr !== nw) {
        if (curr) console.log(`- ${curr}`);
        if (nw) console.log(`+ ${nw}`);
      }
    }
    console.log("--- End of diff ---\n");
    return;
  }

  // Write the updated README
  fs.writeFileSync(README_PATH, newReadme);
  console.log("✏️  README.md updated.");

  // Check git status
  try {
    run("git status --porcelain");
  } catch {
    // If we're not in a git repo, just exit
    return;
  }

  // Configure git and commit
  console.log("🔧 Configuring git...");
  try {
    run(`git config user.name "${AUTHOR_NAME}"`);
    run(`git config user.email "${AUTHOR_EMAIL}"`);
  } catch (e) {
    console.error("⚠️  Could not configure git:", e.message);
    return;
  }

  // Stage and commit
  const branch = `update/prs/${new Date().toISOString().slice(0, 10)}`;
  console.log(`🌿 Checking out branch: ${branch}`);
  run(`git checkout -b ${branch} ${TARGET_BRANCH} 2>/dev/null || git checkout -b ${branch}`);

  run("git add README.md");
  run(
    `git commit -m "docs(readme): update open source contributions [skip ci]"`
  );

  console.log("✅ Committed changes.");

  // Push the branch
  console.log("📤 Pushing branch...");
  try {
    run(`git push origin ${branch}`);
  } catch (e) {
    console.error("⚠️  Could not push branch:", e.message);
    console.log("\n📝 Commit created locally. Branch:", branch);
    return;
  }

  console.log("✅ Branch pushed.");

  // Create PR
  console.log("🔀 Creating pull request...");
  try {
    const prResult = run(
      `gh pr create --base ${TARGET_BRANCH} --head ${branch} --title "docs(readme): update open source contributions" --body "Automatically updated open source contributions section."`
    );
    console.log("✅ Pull request created!");
    console.log(prResult);
  } catch (e) {
    console.error("⚠️  Could not create PR:", e.message);
    console.log("\n📝 Branch pushed. Create PR manually:");
    console.log(`   gh pr create --base ${TARGET_BRANCH} --head ${branch}`);
  }
}

main();
