name: GitHub Metrics
on:
  create:
  push:
  schedule:
    - cron: "23 */7 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: poliglots
          config_timezone: UTC
          output_file: metrics.svg
          template: repository

          # Plugins
          plugins.users.enabled: no
          plugins.achievements.enabled: no
          plugins.achievements.themes: tech
          plugins.sponsor.enabled: no
          plugins.support.enabled: no
          plugins.habits.enabled: no
          plugins.habits.facts.enabled: no
          plugins.infrastructure.used.services.enabled: no
          plugins.infrastructure.used.platforms.enabled: no

          # Base configuration
          base.divider: true
          base.background: 00000000
          base.padding: 25px
          base.header.title: poliglots
          base.header.icon: true
          base.location.country: true

          # Activity
          activity.enabled: yes
          activity.limit: 5
          activity.title: Recent Activity

          # Achievements
          achievements.enabled: yes
          achievements.title: Achievements
          achievements.density: 5
          achievements.layout: compact

          # Repositories
          repositories.enabled: yes
          repositories.title: Repositories
          repositories.layout: compact
          repositories.model: recently_updated
          repositories.stargazers: true
          repositories.forks: true
          repositories.size: true

          # Languages
          languages.enabled: yes
          languages.title: Languages
          languages.limit: 8
          languages.detailed: yes
          languages.icons: yes

          # Open Source
          open_source.enabled: yes
          open_source.title: Open Source Contributions

          # Following
          following.enabled: no
          following.title: Following
          following.limit: 8

          footer: true
          gists: true
